### ISSUE TITLE
failed to run example after make

### ISSUE THREAD

**Issue by zxh0** [yurydelendik/wasmception#10]
`__attribute__((visibility("default")))` doesn't work as expected. [this article](https://aransentin.github.io/cwasm/) says:

> need to add "--export-dynamic" as well to prevent wasm-lld stripping absolutely everything.

and that option solved my problem.

**Comment by yurydelendik** [comment]
Fixed by 2e53cbae1061fcaa400f960fbc84bd93175fb875

Thanks
