### ISSUE TITLE
std::map iterator never finishes

### ISSUE THREAD

**Issue by bubba** [yurydelendik/wasmception#12]
An interesting issue occurs whenever you try to iterate through an `std::map` from `libcxx`:

```cpp
#include <map>
std::map<int, int> x;
extern "C" int foo() {
	x[42] = 32;
	int i = 0;
	for (auto y: x) {
		i++;
		// prevent browser from hanging!
		if (i > 10) break;
	}
	// returns 10 instead of 1
	return i;
}
```

The Makefile used to build it is from the examples folder but for C++:
```makefile
all:
	../dist/bin/clang++ \
		--target=wasm32-unknown-unknown-wasm \
		--sysroot=../sysroot \
		-g \
		-o main.wasm \
		-nostartfiles \
		-Wl,--allow-undefined-file=main.syms,--demangle,--no-entry, \
		-Wl,--export=foo \
		-fvisibility=hidden \
		-fno-exceptions \
		main.cpp
```

It never finishes iterating through this one element map and keeps on placing the same value into `y`. 
Are there any pointers as to where this could be going wrong or where I can start debugging this?

**Comment by yurydelendik** [comment]
The `__wasm_call_ctors` is not called, so the global/static `x` is not initialized. I'm not sure yet what is the consensus and at what point the constructors will be called in the WebAssembly community. (Maybe automatically in the start function?) For the wasmception/wasmstudio, you can call it yourself:

```
extern "C" void __wasm_call_ctors();

__attribute__((visibility("default")))
extern "C" void init() {
  __wasm_call_ctors();
}
```

See https://webassembly.studio/?f=7tumonekl8y for full example. Closing as anwsered.
