### ISSUE TITLE
Accessing WASM Dwarf via Wasmception and Clang

### ISSUE THREAD

**Issue by rohitrastogi** [yurydelendik/wasmception#15]
Hi,

Sorry if this is a simple or obvious question. I'm very new to WASM, LLVM, and DWARF. Can Clang and by extension, Wasmception, be used to generate external Wasm DWARF as described here: https://yurydelendik.github.io/webassembly-dwarf/#dwarf-locals?

If so, what steps need to be taken to generate the Wasm DWARF?

Best,
Rohit

**Comment by yurydelendik** [comment]
> If so, what steps need to be taken to generate the Wasm DWARF?

The patch for LLVM is at https://reviews.llvm.org/D52634 . The rust team landed this and other patch at rust nightly, so you can try it there. I'll try to add D52634 patches to wasmception soon.

**Comment by rohitrastogi** [comment]
Awesome, thank you!
