### ISSUE TITLE
Using object file without linking?

### ISSUE THREAD

**Issue by habemus-papadum** [yurydelendik/wasmception#5]
hi -- thanks for providing wasmexception! 
(for what it's worth, the toolchain build and example worked flawlessly on my MacOS box)

If I just compile and produce just an object file, the object file produced is a wasm archive  e.g. 

```
> ../dist/bin/clang --target=wasm32-unknown-unknown-wasm --sysroot=../sysroot -O3 -g -c main.c
> file main.o
main.o: WebAssembly (wasm) binary module version 0x1 (MVP)
```

Do you know to what extent this wasm file can be used without having to pass it thru `lld`.  This is mostly out of curiosity, as  I was planning  to try an experiment which needs a very streamlined amount of  c/c++ that does not rely on `new/malloc/free` -- but would just need an api that assumes a block of memory has been pre-allocated -- so no system calls, or libc dependencies in my code. In such a case, do you think I could just use the object file directly?

(please let me know if there is better a place to ask this question)

thanks!

**Comment by yurydelendik** [comment]
> do you think I could just use the object file directly?

You cannot use object file directly with WebAssembly.compile and other methods. See https://github.com/WebAssembly/tool-conventions/blob/master/Linking.md . You will need to call `lld` to finalize wasm file (from multiple files) and specify such arguments as memory, tables, external symbols.

>   I was planning to try an experiment  ... does not rely on new/malloc/free 

Just call `clang` for compilation (`-c`), though you need to control what includes are used, so you do not pull musl, libcxx, or other library dependencies (if you do, you will be errors on the lld step). The same goes for the `lld` call, you need to control which object file and libraries is linked. It worked for me in the past.

Closing as anwered.

**Comment by habemus-papadum** [comment]
thanks  -- that's what I wanted to know.
