### ISSUE TITLE
Failed to compile simple C++ code

### ISSUE THREAD

**Issue by michailvoronov** [yurydelendik/wasmception#8]
I am trying to compile the next simple C++ example

```
#include <vector>

int main(int argc, char *argv[]) {
   std::vector<int> vec;
   vec.push_back(1);

   return 0;
}
```

but it fails on linking:

```
wasm-ld: error: /tmp/main-f13943.o: undefined symbol: __cxa_begin_catch
wasm-ld: error: /tmp/main-f13943.o: undefined symbol: __cxa_allocate_exception
wasm-ld: error: /tmp/main-f13943.o: undefined symbol: __cxa_throw
clang-8: error: lld command failed with exit code 1 (use -v to see invocation)
```

It was possible for compilation this example earlier  - i think that [switching](https://github.com/yurydelendik/wasmception/commit/b713bf964756caf3876190126b5308b8fe783c7e) to llvm 8 can be a cause.

**Comment by yurydelendik** [comment]
Using of "-fno-exceptions" will fix the issue. Currently https://github.com/WebAssembly/exception-handling is in works, so compiling any c++ code with exceptions needs to use the above option.

**Comment by michailvoronov** [comment]
Thank you!
