### ISSUE TITLE
malloc returns memory that is out of bounds

### ISSUE THREAD

**Issue by LinusU** [yurydelendik/wasmception#9]
In some cases, `malloc` returns a pointer to a region that doesn't contain enough allocated memory. I've modified the built-in example to trigger that behavior:

https://github.com/yurydelendik/wasmception/compare/master...LinusU:malloc-bug

<img width="690" alt="screenshot 2018-10-12 at 17 29 21" src="https://user-images.githubusercontent.com/189580/46878759-61e07c80-ce44-11e8-8f63-d2bcbd0af9f8.png">

(I've also added a `Dockerfile` in order to try this out on Ubuntu 18.04 without having to set up the environment from scratch. To anyone trying this on macOS: you need to increase the memory given to Docker, otherwise the build will fail. I recommend 8 GB.)

**Comment by yurydelendik** [comment]
After following changes everything works for me:

```
diff --git a/example/index.html b/example/index.html
index e63cec9..917f740 100644
--- a/example/index.html
+++ b/example/index.html
@@ -27,6 +27,7 @@ fetch('main.wasm').then(function(response) {
             };
 
             WebAssembly.instantiate(module, imports).then(function(instance) {
+                window.instance = instance;
                 console.log('MEMORY SIZE BEFORE', instance.exports.memory.buffer.byteLength / 65536)
                 console.log(instance.exports.do_something())
                 console.log('MEMORY SIZE AFTER', instance.exports.memory.buffer.byteLength / 65536)
diff --git a/example/main.c b/example/main.c
index 70f2d6f..16a53a9 100644
--- a/example/main.c
+++ b/example/main.c
@@ -30,19 +30,19 @@ int do_something() {
        uint8_t* a = malloc(1400000);
        sum += a[1400000 - 1];
 
-       sprintf(&str, "%p", a);
+       sprintf(str, "%p", a);
        console_log(str);
 
        uint8_t* b = malloc(999999999);
        sum += b[999999999 - 1];
 
-       sprintf(&str, "%p", b);
+       sprintf(str, "%p", b);
        console_log(str);
 
        uint8_t* c = malloc(1400000);
        sum += c[1400000 - 1];
 
-       sprintf(&str, "%p", c);
+       sprintf(str, "%p", c);
        console_log(str);
 
        uint8_t* d = malloc(1400000);
```

Closing as invalid.

**Comment by LinusU** [comment]
Now I feel really stupid 🤦‍♂️ sorry about that.

I still think that there is a bug somewhere though, but quite possible in my code, because I'm still getting the out of bounds error in my very small bindings to libwebp: https://github.com/LinusU/cwasm-webp

I'll keep digging!

**Comment by yurydelendik** [comment]
> I'll keep digging!

Try use debugger, e.g. Firefox's debugger can break on caught exceptions and WebAssembly exceptions one of them, it will point to the offending instruction -- that's how I fixed your example.

It is possible to use source map/DWARF too in Nightly, but it requires more configuration to your build process. See e.g. https://github.com/yurydelendik/sqlite-playground/blob/master/Makefile
